
### Tomcat
server:
  port: 50012
  servlet:
    context-path: /

### 环境
spring:
  application:
    name: project-test
  # 环境的选择   dev | prod
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

### 对swagger-ui 增强 生产环境变成true,或者开启验证
knife4j:
  production: false
  basic:
    enable: true
    username: admin
    password: 123


### mybatis  因为引用了plus 所以这里要用 plus 配置
mybatis-plus:
  mapper-locations: com/summit/content/*/mapper/*.xml
  type-aliases-package: com.summit
  configuration:
    map-underscore-to-camel-case: true


